version: "3"
services: 
    frontend:
        image: jiewuu/circles-client:1.4
        stdin_open: true
        restart: always
        ports: 
            - "3000:3000"
        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules
        links:
            - backend
        networks:
            - circles_network
    
    backend:
        image: jiewuu/circles-api:2.3
        restart: always
        ports: 
            - "5000:5000"
        env_file: ./backend/.env
        volumes:
            - ./backend:/backend
            - /backend/node_modules
        depends_on:
            - elasticsearch
        networks:
            - circles_network
        
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        ports:
            - "27017:27017"
        command: mongod --noauth
        networks:
            - circles_network
    
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.8.10
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
        networks:
            - circles_network
            
networks:
    circles_network:
        driver: bridge
