version: "2"
services: 
    frontend:
        image: jiewuu/circles-client:1.3
        stdin_open: true
        restart: always
        ports: 
            - "3000:3000"
        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules
        links:
            - backend
        networks:
            - circles_network
    
    backend:
        image: jiewuu/circles-api:1.2
        restart: always
        ports: 
            - "5000:5000"
        volumes:
            - ./backend:/backend
            - /backend/node_modules
        depends_on:
            - mongodb
            - elasticsearch
            - redis
        networks:
            - circles_network
        
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        ports:
            - "27017:27017"
        command: mongod --noauth
        networks:
            - circles_network
    
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - "9200:9200"
        networks:
            - circles_network

    redis:
        image: redis
        container_name: cache
        expose:
            - 6379
    
networks:
    circles_network:
        driver: bridge
