version: "2"
services: 
    frontend:
        image: jiewuu/circles-client:4.1
        stdin_open: true
        restart: always
        ports: 
            - "3000:3000"
        volumes:
            - ./frontend:/frontend
            - /frontend/node_modules
        links:
            - backend
        networks:
            - circles_network
    
    backend:
        image: jiewuu/circles-api:3.3
        restart: always
        ports: 
            - "5000:5000"
        volumes:
            - ./backend:/backend
            - /backend/node_modules
        networks:
            - circles_network
    
networks:
    circles_network:
        driver: bridge
